Comandos:
  Alerta:
    Sem_Permissao: '&c➥ Você não tem permissão para executar este comando.'
    Erro: '&c➥ Erro! Use: /alerta <mensagem>'
    Mensagem:
    - ' '
    - '&4&lAVISO: &c{mensagem}'
    - ' '
  
  ClearChat:
    Sem_Permissao: '&c➥ Você não tem permissão para executar este comando.'
    Sucesso: '&a➥ Você limpou o chat com sucesso!'
    
  Online:
    Mensagem: '§a➥ Atualmente temos §e{quantidade} §aJogadores online.'