name: Essenciais
version: 1.0.3
author: [TantsZ]
main: me.tantsz.essenciais.Main

commands:
  alert:
    aliases: [alerta, alertar]
  clearchat:
    aliases: [cc, limparchat]
  cleardrops:
  clearmobs:
  craft:
    aliases: [craftable, workbench]
  online:
    aliases: [on, ons]